/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import DAO.Conexao;
import DAO.OperacoesDAO;
import controller.ControllerExtrato;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import model.Extrato;
import java.sql.SQLException;
import java.sql.Connection;
import view.JanelaExtrato;
/**
 *
 * @author kawan
 */
public class JanelaExtrato extends javax.swing.JFrame {
    private Extrato extrato;
    private String cpfCliente;
    private OperacoesDAO operacoesDAO;
    private JanelaExtrato janelaExtrato;
    /**
     * Creates new form JanelaExtrato
     */
     public JanelaExtrato(Extrato extrato, String cpfCliente) throws SQLException {
        this.extrato = extrato;
        this.cpfCliente = cpfCliente;
        this.operacoesDAO = new OperacoesDAO(Conexao.getConnection());
        this.c = new ControllerExtrato(this); // Passe a instância da janela para o controller
        initComponents();
    }
    public JButton getBtConsultarExtrato() {
        return btConsultarExtrato;
    }

    public void setBtConsultarExtrato(JButton btConsultarExtrato) {
        this.btConsultarExtrato = btConsultarExtrato;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JTextArea getLblExtrato() {
        return lblExtrato;
    }

    public void setLblExtrato(JTextArea lblExtrato) {
        this.lblExtrato = lblExtrato;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btConsultarExtrato = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblExtrato = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setText("Consultar Extrato da carteira de investimentos");

        btConsultarExtrato.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btConsultarExtrato.setText("Consultar Extrato");
        btConsultarExtrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarExtratoActionPerformed(evt);
            }
        });

        lblExtrato.setColumns(20);
        lblExtrato.setRows(5);
        jScrollPane1.setViewportView(lblExtrato);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(btConsultarExtrato, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btConsultarExtrato, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btConsultarExtratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarExtratoActionPerformed
         try {
        // Realize a consulta ao banco de dados para obter o extrato
        Extrato extrato = operacoesDAO.consultarExtrato(cpfCliente); // Substitua "cpfCliente" pelo CPF do cliente
     
        // Exiba o extrato chamando a função exibirExtrato
        c.exibirExtrato(extrato);
    } catch (SQLException e) {
        // Trate o erro ao consultar o extrato
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Erro ao consultar extrato do cliente.");
    }
    }//GEN-LAST:event_btConsultarExtratoActionPerformed

  
    ControllerExtrato c;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConsultarExtrato;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea lblExtrato;
    // End of variables declaration//GEN-END:variables
}
